server:
  port: 9090

---
springbootwebfluxjjwt:
  password:
    encoder:
      secret: "mysecret"
      iteration: 33
      keylength: 256
---
spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
---    
password:
  min-length: 8
  max-length: 20
  require-uppercase: true
  require-lowercase: true
  require-digit: true
  require-special: true    